apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: atlantis
  name: atlantis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: atlantis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: atlantis
    spec:
      containers:
        - args:
            - server
            - --gh-user=${GITHUB_USER}
            - --gh-token=${GITHUB_TOKEN}
            - --repo-allowlist=${GITHUB_REPO_ALLOWLIST}
            - --repo-config=/usr/local/bin/repos.yaml
          env:
            - name: SSH_AUTH_SOCK
              value: /ssh-agent
            - name: URL
              value: ${NGROK_URL}
          image: atlantis:latest
          name: atlantis
          ports:
            - containerPort: 4141
              protocol: TCP
          volumeMounts:
            - mountPath: /.ssh
              name: atlantis-cm0
              readOnly: true
            - mountPath: /atlantis/src
              name: atlantis-cm1
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            name: atlantis-cm0
          name: atlantis-cm0
        - configMap:
            name: atlantis-cm1
          name: atlantis-cm1
