apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: atlantis
  name: atlantis
spec:
  ports:
    - name: "4141"
      port: 4141
      targetPort: 4141
  selector:
    io.kompose.service: atlantis
