apiVersion: v1
data:
  docker-compose.yaml: "services:\n  atlantis:\n    image: azure.azurecr.io/atlantis:v2\n    command:\n      - \"server\" \n      - \"--gh-user=${GITHUB_USER}\"\n      - \"--gh-token=${GITHUB_TOKEN}\" \n      - \"--repo-allowlist=${GITHUB_REPO_ALLOWLIST}\"\n      - \"--repo-config=/usr/local/bin/repos.yaml\"\n    build: .\n    ports:\n      - \"4141:4141\"\n    restart: always\n    volumes:\n      - ${HOME}/.ssh:/atlantis/.ssh:ro\n      - ${PWD}:/atlantis/src:ro\n      - /run/host-services/ssh-auth.sock # Forward local machine SSH key to docker\n    environment:\n   SSH_AUTH_SOCK: /ssh-agent\n"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: atlantis
  name: atlantis-cm1
