apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlantis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlantis
  template:
    metadata:
      labels:
        app: atlantis
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: atlantis
        image: atlantis:latest
        ports:
        - containerPort: 4141
        volumes:
          - ${HOME}/.ssh:/.ssh:ro
          - ${PWD}:/atlantis/src:ro
          - /run/host-services/ssh-auth.sock # Forward local machine SSH key to docker
        environment:
          - URL="https://f9ef-2601-601-1501-1a10-f5e3-e7d4-6294-f5a8.ngrok-free.app"
          - SSH_AUTH_SOCK="/ssh-agent"
          # name: atlantis
        # env: 
        # - name: VUE_APP_ORDER_SERVICE_URL
        #   value: "http://order-service:3000/"
        # - name: VUE_APP_PRODUCT_SERVICE_URL
        #   value: "http://product-service:3002/"
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: njuma-front
# spec:
#   ports:
#   - port: 80
#     targetPort: 8000
#   selector:
#     app: njuma-front
#   type: LoadBalancer