# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: external-secret
#   namespace: atlantis
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     kind: SecretStore
#     name: secret-store
#   target:
#     name: atlantis-secret
#     #creationPolicy: Owner
#   data:
#   - secretKey: POSTGRES_HOST
#     remoteRef:
#       key: atlantis-postgres-host
#   - secretKey: POSTGRES_PORT
#     remoteRef:
#       key: atlantis-postgres-port
#   - secretKey: POSTGRES_USER
#     remoteRef:
#       key: atlantis-postgres-user
#   - secretKey: POSTGRES_PASSWORD
#     remoteRef:
#       key: atlantis-postgres-password
#   - secretKey: DD_CLIENT_TOKEN
#     remoteRef:
#       key: atlantis-dd-client-token
#   - secretKey: DD_APPLICATION_ID
#     remoteRef:
#       key: atlantis-dd-application-id
#   - secretKey: DD_SITE
#     remoteRef:
#       key: atlantis-dd-site
#   - secretKey: DD_ENV
#     remoteRef:
#       key: atlantis-dd-env
#   - secretKey: GITHUB_TOKEN
#     remoteRef:
#       key: atlantis-github-token
#   - secretKey: AZURE_TOKEN
#     remoteRef:
#       key: atlantis-azure-token
