apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: client-id #4205daac-a5e8-49da-87ec-1f7d53426797
    azure.workload.identity/tenant-id: tenant-id
  labels:
    azure.workload.identity/use: "true"
  name: backstage-sa
  namespace: backstage
