apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: client-id  # TODO: Replace with actual client ID
    azure.workload.identity/tenant-id: tenant-id  # TODO: Replace with actual tenant ID
  labels:
    azure.workload.identity/use: "true"
  name: atlantis-sa
  namespace: atlantis
